Refactor Result class
WebAssembly/wasi-testsuite pull request #51
Opened 2023-01-31 09:16 UTC by yamt

I plan to add "timed out" case to the union later.

todo:
* update tests
* update json reporter

2023-02-03 04:49 UTC, yamt commented
@loganek do you have any early feedback about the api?

2023-02-03 10:26 UTC, loganek commented
> @loganek do you have any early feedback about the api?

I left a few comments. It looks ok to me in general, although I'm not really sure if we should have yet another type in the `Result` union for timeout - after all, it is a failure, right?

2023-02-03 10:26 UTC, loganek requested changes

2023-02-03 10:26 UTC, loganek commented on test-runner/wasi_test_runner/test_case.py
> +class Executed(NamedTuple):
```suggestion
class ExecutedResult(NamedTuple):
```

2023-02-03 10:26 UTC, loganek commented on test-runner/wasi_test_runner/test_case.py
> +class Skipped(NamedTuple):
```suggestion
class SkippedResult(NamedTuple):
```

2023-02-03 10:26 UTC, loganek commented on test-runner/wasi_test_runner/test_case.py
> +Result = Union[Executed, Skipped]
```suggestion
Result = Union[ExecutedResult, SkippedResult]
```

2023-02-03 10:26 UTC, loganek commented on test-runner/wasi_test_runner/test_case.py
> -    def failed(self) -> bool:
I'd keep that property for the `Executed` class as it abstracts the implementation detail.

2026-06-10 07:36 UTC, vados-cosmonic commented
Closing this out as the test suite has changed dramatically (been buckified, scripts work differently, etc)

Happy to re-open if the issue is still present, but I don't think this PR could ever be merged in the current state (it's also been 3 years!)

2026-06-10 07:36 UTC, closed without merging